const fetch=require('node-fetch');

const headers={'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'OPTIONS,POST'};
const CATALOG_TYPES=new Set(['generic','services','products','menu','properties','courses','vehicles','packages']);
const AVAILABILITY=new Set(['available','unavailable','on_request','sold_out','paused']);
function reply(c,b){return{statusCode:c,headers,body:JSON.stringify(b)}}
function clean(v,max=0){const s=String(v||'').replace(/\s+/g,' ').trim();return max?s.slice(0,max):s}
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
function bool(v,def=false){return typeof v==='boolean'?v:def}
function money(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)&&n>=0?Math.round(n*100)/100:null}
async function db(path,opt={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase service role não configurado.');return fetch(url+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key,...(opt.headers||{})}})}
async function rows(res,label){if(!res.ok)throw new Error(label+': '+(await res.text()).slice(0,700));const raw=await res.text();return raw?JSON.parse(raw):[]}
async function auth(botId,token){const q='website_bots?bot_id=eq.'+encodeURIComponent(botId)+'&client_token=eq.'+encodeURIComponent(token)+'&select=bot_id,company_name&limit=1';return(await rows(await db(q),'validar SmartBot'))[0]||null}
async function getConfig(botId){return(await rows(await db('smartbot_catalog_config?bot_id=eq.'+encodeURIComponent(botId)+'&select=*&limit=1'),'config catálogo'))[0]||null}
async function getItems(botId){return rows(await db('smartbot_catalog_items?bot_id=eq.'+encodeURIComponent(botId)+'&select=*&order=sort_order.asc,created_at.asc&limit=500'),'itens catálogo')}
function formatPrice(item,config){if(item.price===null||item.price===undefined||config.show_prices===false)return'';return ` | Preço: ${item.currency||config.currency||'BRL'} ${Number(item.price).toFixed(2)}`}
function formatAttrs(attrs){const pairs=Object.entries(obj(attrs)).filter(([,v])=>v!==null&&v!==undefined&&String(v).trim()!=='').slice(0,16);return pairs.length?' | Detalhes: '+pairs.map(([k,v])=>`${k}: ${String(v).slice(0,180)}`).join('; '):''}
async function syncKnowledge(botId){
  const config=await getConfig(botId),items=await getItems(botId),title='Catálogo estruturado — fonte autoritativa';
  const existing=await rows(await db('smartbot_knowledge?bot_id=eq.'+encodeURIComponent(botId)+'&title=eq.'+encodeURIComponent(title)+'&select=id&limit=1'),'knowledge catálogo');
  if(!config||config.enabled!==true){if(existing[0])await db('smartbot_knowledge?id=eq.'+encodeURIComponent(existing[0].id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_active:false,updated_at:new Date().toISOString()})});return}
  const active=items.filter(x=>x.active===true),lines=[`CATÁLOGO ESTRUTURADO: ${config.display_name||'Catálogo'}`,`Tipo: ${config.catalog_type||'generic'}`,`Moeda: ${config.currency||'BRL'}`,`Mostrar preços: ${config.show_prices!==false?'sim':'não'}`];
  if(config.notes)lines.push(`Regras do catálogo: ${config.notes}`);
  lines.push('IMPORTANTE: para preço, disponibilidade, categoria e detalhes dos itens abaixo, trate este catálogo como fonte atual do negócio. Não invente itens nem disponibilidade.');
  for(const item of active.slice(0,250))lines.push(`- ${item.name}${item.category?` | Categoria: ${item.category}`:''}${formatPrice(item,config)} | Disponibilidade: ${item.availability_status||'available'}${item.description?` | ${item.description}`:''}${formatAttrs(item.attributes)}`);
  if(!active.length)lines.push('- Nenhum item ativo cadastrado no momento.');
  const payload={bot_id:botId,title,content:lines.join('\n').slice(0,60000),source_type:'manual',is_active:true,updated_at:new Date().toISOString()};
  if(existing[0])await rows(await db('smartbot_knowledge?id=eq.'+encodeURIComponent(existing[0].id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}),'atualizar knowledge catálogo');
  else await rows(await db('smartbot_knowledge',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}),'criar knowledge catálogo');
}
async function saveConfig(botId,body){const current=await getConfig(botId),catalogType=CATALOG_TYPES.has(clean(body.catalogType))?clean(body.catalogType):(current?.catalog_type||'generic'),payload={bot_id:botId,enabled:bool(body.enabled,current?.enabled===true),catalog_type:catalogType,display_name:clean(body.displayName,120)||current?.display_name||'Catálogo',currency:clean(body.currency,8).toUpperCase()||current?.currency||'BRL',show_prices:bool(body.showPrices,current?.show_prices!==false),notes:clean(body.notes,3000)||null,updated_at:new Date().toISOString()};let saved;if(current)saved=await rows(await db('smartbot_catalog_config?bot_id=eq.'+encodeURIComponent(botId),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}),'salvar config catálogo');else saved=await rows(await db('smartbot_catalog_config',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}),'criar config catálogo');await syncKnowledge(botId);return saved[0]}
function itemPayload(botId,body){const availability=AVAILABILITY.has(clean(body.availabilityStatus))?clean(body.availabilityStatus):'available';return{bot_id:botId,item_type:clean(body.itemType,80)||'item',external_key:clean(body.externalKey,160)||null,sku:clean(body.sku,120)||null,name:clean(body.name,240),category:clean(body.category,160)||null,description:clean(body.description,3000)||null,price:money(body.price),currency:clean(body.currency,8).toUpperCase()||'BRL',availability_status:availability,attributes:obj(body.attributes),source:clean(body.source,40)||'manual',active:body.active!==false,sort_order:Number.isFinite(Number(body.sortOrder))?Math.trunc(Number(body.sortOrder)):0,updated_at:new Date().toISOString()}}
async function saveItem(botId,body){const payload=itemPayload(botId,body);if(!payload.name)throw new Error('Nome do item é obrigatório.');let saved;if(body.id){const owned=await rows(await db('smartbot_catalog_items?id=eq.'+encodeURIComponent(body.id)+'&bot_id=eq.'+encodeURIComponent(botId)+'&select=id&limit=1'),'validar item');if(!owned[0])throw new Error('Item não encontrado.');saved=await rows(await db('smartbot_catalog_items?id=eq.'+encodeURIComponent(body.id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}),'atualizar item')}else saved=await rows(await db('smartbot_catalog_items',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}),'criar item');await syncKnowledge(botId);return saved[0]}
async function removeItem(botId,id){const owned=await rows(await db('smartbot_catalog_items?id=eq.'+encodeURIComponent(id)+'&bot_id=eq.'+encodeURIComponent(botId)+'&select=id&limit=1'),'validar item');if(!owned[0])throw new Error('Item não encontrado.');await rows(await db('smartbot_catalog_items?id=eq.'+encodeURIComponent(id),{method:'DELETE',headers:{Prefer:'return=representation'}}),'remover item');await syncKnowledge(botId)}
async function bulkImport(botId,items){const safe=Array.isArray(items)?items.slice(0,300):[];let count=0;for(const raw of safe){const payload=itemPayload(botId,{...raw,source:'import'});if(!payload.name)continue;await rows(await db('smartbot_catalog_items',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)}),'importar item');count++}await syncKnowledge(botId);return count}
exports.handler=async event=>{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers,body:''};if(event.httpMethod!=='POST')return reply(405,{success:false,error:'Method Not Allowed'});try{const body=JSON.parse(event.body||'{}'),botId=clean(body.botId,140),clientToken=clean(body.clientToken,240),action=clean(body.action||'get');if(!botId||!clientToken)return reply(400,{success:false,error:'botId e clientToken são obrigatórios.'});const bot=await auth(botId,clientToken);if(!bot)return reply(403,{success:false,error:'Acesso negado.'});if(action==='get'){const [config,items]=await Promise.all([getConfig(botId),getItems(botId)]);return reply(200,{success:true,companyName:bot.company_name,config:config||{enabled:false,catalog_type:'generic',display_name:'Catálogo',currency:'BRL',show_prices:true,notes:''},items})}if(action==='save_config')return reply(200,{success:true,config:await saveConfig(botId,body)});if(action==='save_item')return reply(200,{success:true,item:await saveItem(botId,body)});if(action==='delete_item'){await removeItem(botId,clean(body.id,100));return reply(200,{success:true})}if(action==='bulk_import')return reply(200,{success:true,imported:await bulkImport(botId,body.items)});return reply(422,{success:false,error:'Ação inválida.'})}catch(error){console.error('[CatalogManager]',error.message);return reply(500,{success:false,error:error.message||'Falha no catálogo.'})}};
