const fetch=require('node-fetch');
const {WhatsAppClient}=require('@kapso/whatsapp-cloud-api');

const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*'};
function reply(c,b){return{statusCode:c,headers,body:JSON.stringify(b)}}
function clean(v){return String(v||'').trim()}
function digits(v){return clean(v).replace(/\D/g,'')}
function env(name){return process.env[name]||''}
async function db(path,opt={}){const url=env('SUPABASE_URL'),key=env('SUPABASE_SERVICE_ROLE_KEY')||env('SUPABASE_ANON_KEY');if(!url||!key)throw new Error('Supabase nao configurado');return fetch(url+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key,...(opt.headers||{})}})}
async function createAudit(data){try{const r=await db('smartbot_kapso_webhook_events',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(data)});if(!r.ok)return null;const rows=await r.json();return rows[0]&&rows[0].id}catch(e){return null}}
async function updateAudit(id,status,error){if(!id)return;try{await db('smartbot_kapso_webhook_events?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status,error:error||null,processed_at:new Date().toISOString()})})}catch(e){}}
async function botForPhone(phoneNumberId){if(phoneNumberId){const r=await db('smartbot_whatsapp_config?provider_phone_number_id=eq.'+encodeURIComponent(phoneNumberId)+'&provider=eq.kapso&select=*&limit=1');const a=r.ok?await r.json():[];if(a[0])return a[0]}const fallback=clean(env('KAPSO_DEFAULT_BOT_ID'));if(!fallback)return null;const r=await db('smartbot_whatsapp_config?bot_id=eq.'+encodeURIComponent(fallback)+'&select=*&limit=1');const a=r.ok?await r.json():[];return a[0]||{bot_id:fallback,auto_reply:false}}
function textFromMessage(m){return clean((m&&m.text&&m.text.body)||(m&&m.kapso&&m.kapso.content)||(m&&m.body)||'')}
function v2Inbound(raw){if(!raw||!raw.message||!raw.phone_number_id)return null;const m=raw.message;const direction=clean(m&&m.kapso&&m.kapso.direction);if(direction&&direction!=='inbound')return null;const conv=raw.conversation||{};return{phoneNumberId:clean(raw.phone_number_id||conv.phone_number_id),phone:digits(conv.phone_number||m.from||m.wa_id),name:clean(conv.contact_name||conv.username),text:textFromMessage(m),message:m}}
async function upsertInbox(botId,phone,name,text,intent){const r=await db('smartbot_whatsapp_inbox?bot_id=eq.'+encodeURIComponent(botId)+'&contact_phone=eq.'+encodeURIComponent(phone)+'&limit=1');const rows=r.ok?await r.json():[];const patch={bot_id:botId,contact_phone:phone,contact_name:name,last_message:text,intent,status:'new',source:'whatsapp_kapso',updated_at:new Date().toISOString()};let w;if(rows[0])w=await db('smartbot_whatsapp_inbox?id=eq.'+rows[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});else w=await db('smartbot_whatsapp_inbox',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});if(!w.ok)throw new Error(await w.text());return (await w.json())[0]}
async function saveInbound(botId,inbox,phone,name,text,msg,raw){const r=await db('smartbot_whatsapp_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({bot_id:botId,inbox_id:inbox&&inbox.id,direction:'inbound',contact_phone:phone,contact_name:name,message:text,provider:'kapso',provider_message_id:clean(msg&&msg.id)||null,payload:raw})});if(!r.ok)throw new Error(await r.text())}
async function callBrain(botId,phone,text){try{const r=await fetch((env('URL')||'https://smartbots.club')+'/.netlify/functions/smartbot-brain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({botId,visitorId:'wa_'+phone,channel:'whatsapp',message:text})});const j=await r.json().catch(()=>({success:false}));if(!r.ok)return{success:false,error:j.error||('brain http '+r.status)};return j}catch(e){return{success:false,error:e.message}}}
async function sendReply(phoneNumberId,to,body){const apiKey=env('KAPSO_API_KEY');if(!apiKey||!phoneNumberId||!body)return null;const client=new WhatsAppClient({baseUrl:'https://api.kapso.ai/meta/whatsapp',kapsoApiKey:apiKey});return client.messages.sendText({phoneNumberId,to,body})}
async function handleInbound(item,raw){if(!item||!item.phoneNumberId||!item.phone||!item.text)return{handled:false,reason:'missing inbound fields'};const cfg=await botForPhone(item.phoneNumberId);if(!cfg||!cfg.bot_id)return{handled:false,reason:'numero Kapso nao associado a bot SmartBots'};const brain=await callBrain(cfg.bot_id,item.phone,item.text);const intent=clean(brain.intent)||'duvida';const inbox=await upsertInbox(cfg.bot_id,item.phone,item.name,item.text,intent);await saveInbound(cfg.bot_id,inbox,item.phone,item.name,item.text,item.message,raw);if(cfg.auto_reply===true&&brain.success&&brain.reply){const sent=await sendReply(item.phoneNumberId,item.phone,brain.reply);await db('smartbot_whatsapp_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({bot_id:cfg.bot_id,inbox_id:inbox.id,direction:'outbound',contact_phone:item.phone,contact_name:item.name,message:brain.reply,provider:'kapso',provider_message_id:clean(sent&&sent.messages&&sent.messages[0]&&sent.messages[0].id)||null,payload:sent})}).catch(()=>null)}return{handled:true,inboxId:inbox.id,intent,brainSuccess:!!brain.success,brainError:brain.error||null}}
exports.handler=async(ev)=>{if(ev.httpMethod!=='POST')return reply(200,{success:true});const eventName=clean((ev.headers&&(ev.headers['x-webhook-event']||ev.headers['X-Webhook-Event']))||'');const idem=clean((ev.headers&&(ev.headers['x-idempotency-key']||ev.headers['X-Idempotency-Key']))||'');let raw;try{raw=JSON.parse(ev.body||'{}')}catch(e){raw={_invalid_json:true,_body:String(ev.body||'').slice(0,2000)}}const isBatch=((ev.headers&&String(ev.headers['x-webhook-batch']||'').toLowerCase()==='true')||raw.batch===true);const payloads=isBatch&&Array.isArray(raw.data)?raw.data:[raw];const preAudit=[];for(const payload of payloads){preAudit.push(await createAudit({event_name:eventName||null,idempotency_key:idem||null,is_batch:isBatch,phone_number_id:clean(payload&&payload.phone_number_id)||null,status:'received',payload}))}const expected=clean(env('KAPSO_WEBHOOK_TOKEN'));const supplied=clean((ev.queryStringParameters&&ev.queryStringParameters.token)||'');if(expected&&supplied!==expected){for(const id of preAudit)await updateAudit(id,'unauthorized','webhook token mismatch');return reply(401,{success:false,error:'Webhook token invalido'})}let handled=0;const results=[];for(let i=0;i<payloads.length;i++){const payload=payloads[i],auditId=preAudit[i];try{if(eventName&&eventName!=='whatsapp.message.received'){await updateAudit(auditId,'ignored',null);results.push({handled:false,reason:'event ignored'});continue}const item=v2Inbound(payload);if(!item){await updateAudit(auditId,'ignored','not inbound message');results.push({handled:false,reason:'not inbound message'});continue}const r=await handleInbound(item,payload);if(r.handled)handled++;await updateAudit(auditId,r.handled?'processed':'ignored',r.reason||r.brainError||null);results.push(r)}catch(e){await updateAudit(auditId,'error',e.message);results.push({handled:false,error:e.message})}}
return reply(200,{success:true,handled,batch:isBatch,count:payloads.length,results})};
