const fetch=require('node-fetch');
const {WhatsAppClient}=require('@kapso/whatsapp-cloud-api');
const {normalizeWebhook}=require('@kapso/whatsapp-cloud-api/server');

const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*'};
function reply(c,b){return{statusCode:c,headers,body:JSON.stringify(b)}}
function clean(v){return String(v||'').trim()}
function digits(v){return clean(v).replace(/\D/g,'')}
async function db(path,opt={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase nao configurado');return fetch(url+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key,...(opt.headers||{})}})}
function rawPhoneNumberId(p){try{return clean(p.entry&&p.entry[0]&&p.entry[0].changes&&p.entry[0].changes[0]&&p.entry[0].changes[0].value&&p.entry[0].changes[0].value.metadata&&p.entry[0].changes[0].value.metadata.phone_number_id)}catch(e){return''}}
async function botForPhone(phoneNumberId){if(phoneNumberId){const r=await db('smartbot_whatsapp_config?provider_phone_number_id=eq.'+encodeURIComponent(phoneNumberId)+'&provider=eq.kapso&select=*&limit=1');const a=r.ok?await r.json():[];if(a[0])return a[0]}const fallback=clean(process.env.KAPSO_DEFAULT_BOT_ID);if(!fallback)return null;const r=await db('smartbot_whatsapp_config?bot_id=eq.'+encodeURIComponent(fallback)+'&select=*&limit=1');const a=r.ok?await r.json():[];return a[0]||{bot_id:fallback,auto_reply:false}}
function textFromMessage(m){return clean((m&&m.text&&m.text.body)||(m&&m.kapso&&m.kapso.content)||(m&&m.body)||'')}
function v2Inbound(raw){if(!raw||!raw.message||!raw.phone_number_id)return null;const m=raw.message;if(m.kapso&&m.kapso.direction&&m.kapso.direction!=='inbound')return null;const conv=raw.conversation||{};const ck=conv.kapso||{};return{phoneNumberId:clean(raw.phone_number_id||conv.phone_number_id),phone:digits(conv.phone_number||m.from),name:clean(ck.contact_name||ck.contactName),text:textFromMessage(m),message:m}}
function metaInbound(raw){const events=normalizeWebhook(raw);const out=[];for(const m of (events.messages||[])){if(m.kapso&&m.kapso.direction==='outbound')continue;const c=(events.contacts||[])[0]||{};out.push({phoneNumberId:rawPhoneNumberId(raw)||clean(process.env.KAPSO_PHONE_NUMBER_ID),phone:digits(m.from),name:clean((c.profile&&c.profile.name)||(m.kapso&&m.kapso.contactName)),text:textFromMessage(m),message:m})}return{items:out,statuses:(events.statuses||[]).length}}
async function upsertInbox(botId,phone,name,text,intent){const r=await db('smartbot_whatsapp_inbox?bot_id=eq.'+encodeURIComponent(botId)+'&contact_phone=eq.'+encodeURIComponent(phone)+'&limit=1');const rows=r.ok?await r.json():[];const patch={bot_id:botId,contact_phone:phone,contact_name:name,last_message:text,intent,status:'new',source:'whatsapp_kapso',updated_at:new Date().toISOString()};let w;if(rows[0])w=await db('smartbot_whatsapp_inbox?id=eq.'+rows[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});else w=await db('smartbot_whatsapp_inbox',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});if(!w.ok)throw new Error(await w.text());return (await w.json())[0]}
async function saveInbound(botId,inbox,phone,name,text,msg,raw){await db('smartbot_whatsapp_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({bot_id:botId,inbox_id:inbox&&inbox.id,direction:'inbound',contact_phone:phone,contact_name:name,message:text,provider:'kapso',provider_message_id:clean(msg&&msg.id)||null,payload:raw})}).catch(()=>null)}
async function callBrain(botId,phone,text){const r=await fetch((process.env.URL||'https://smartbots.club')+'/.netlify/functions/smartbot-brain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({botId,visitorId:'wa_'+phone,channel:'whatsapp',message:text})});return r.json().catch(()=>({success:false}))}
async function sendReply(phoneNumberId,to,body){const apiKey=process.env.KAPSO_API_KEY;if(!apiKey||!phoneNumberId||!body)return null;const client=new WhatsAppClient({baseUrl:'https://api.kapso.ai/meta/whatsapp',kapsoApiKey:apiKey});return client.messages.sendText({phoneNumberId,to,body})}
async function handleInbound(item,raw){if(!item||!item.phoneNumberId||!item.phone||!item.text)return{handled:false,reason:'missing inbound fields'};const cfg=await botForPhone(item.phoneNumberId);if(!cfg||!cfg.bot_id)return{handled:false,reason:'numero Kapso nao associado a bot SmartBots'};const brain=await callBrain(cfg.bot_id,item.phone,item.text);const intent=clean(brain.intent)||'duvida';const inbox=await upsertInbox(cfg.bot_id,item.phone,item.name,item.text,intent);await saveInbound(cfg.bot_id,inbox,item.phone,item.name,item.text,item.message,raw);if(cfg.auto_reply===true&&brain.success&&brain.reply){const sent=await sendReply(item.phoneNumberId,item.phone,brain.reply);await db('smartbot_whatsapp_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({bot_id:cfg.bot_id,inbox_id:inbox.id,direction:'outbound',contact_phone:item.phone,contact_name:item.name,message:brain.reply,provider:'kapso',provider_message_id:clean(sent&&sent.messages&&sent.messages[0]&&sent.messages[0].id)||null,payload:sent})}).catch(()=>null)}return{handled:true,inboxId:inbox.id,intent}}
exports.handler=async(ev)=>{if(ev.httpMethod!=='POST')return reply(200,{success:true});try{const expected=clean(process.env.KAPSO_WEBHOOK_TOKEN);const supplied=clean((ev.queryStringParameters&&ev.queryStringParameters.token)||'');if(expected&&supplied!==expected)return reply(401,{success:false,error:'Webhook token invalido'});const raw=JSON.parse(ev.body||'{}');let items=[],statuses=0;const v2=v2Inbound(raw);if(v2){items=[v2]}else{const parsed=metaInbound(raw);items=parsed.items;statuses=parsed.statuses}const results=[];for(const item of items)results.push(await handleInbound(item,raw));return reply(200,{success:true,handled:results.filter(x=>x.handled).length,statuses,results})}catch(e){return reply(500,{success:false,error:e.message})}};
