const fetch=require('node-fetch');
const {WhatsAppClient}=require('@kapso/whatsapp-cloud-api');
const {normalizeWebhook}=require('@kapso/whatsapp-cloud-api/server');

const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*'};
function reply(c,b){return{statusCode:c,headers,body:JSON.stringify(b)}}
function clean(v){return String(v||'').trim()}
async function db(path,opt={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase nao configurado');return fetch(url+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key,...(opt.headers||{})}})}
function rawPhoneNumberId(p){try{return clean(p.entry&&p.entry[0]&&p.entry[0].changes&&p.entry[0].changes[0]&&p.entry[0].changes[0].value&&p.entry[0].changes[0].value.metadata&&p.entry[0].changes[0].value.metadata.phone_number_id)}catch(e){return''}}
async function botForPhone(phoneNumberId){if(phoneNumberId){const r=await db('smartbot_whatsapp_config?provider_phone_number_id=eq.'+encodeURIComponent(phoneNumberId)+'&provider=eq.kapso&select=*&limit=1');const a=r.ok?await r.json():[];if(a[0])return a[0]}const fallback=clean(process.env.KAPSO_DEFAULT_BOT_ID);if(!fallback)return null;const r=await db('smartbot_whatsapp_config?bot_id=eq.'+encodeURIComponent(fallback)+'&select=*&limit=1');const a=r.ok?await r.json():[];return a[0]||{bot_id:fallback,auto_reply:false}}
function messageText(m){return clean((m.text&&m.text.body)||(m.kapso&&m.kapso.content)||m.body||'')}
function contactName(events,m){const c=(events.contacts||[])[0]||{};return clean((c.profile&&c.profile.name)||(m.kapso&&m.kapso.contactName)||'')}
async function upsertInbox(botId,phone,name,text,intent){const r=await db('smartbot_whatsapp_inbox?bot_id=eq.'+encodeURIComponent(botId)+'&contact_phone=eq.'+encodeURIComponent(phone)+'&limit=1');const rows=r.ok?await r.json():[];const patch={bot_id:botId,contact_phone:phone,contact_name:name,last_message:text,intent,status:'new',source:'whatsapp_kapso',updated_at:new Date().toISOString()};let w;if(rows[0])w=await db('smartbot_whatsapp_inbox?id=eq.'+rows[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});else w=await db('smartbot_whatsapp_inbox',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});if(!w.ok)throw new Error(await w.text());return (await w.json())[0]}
async function saveInbound(botId,inbox,phone,name,text,msg,raw){await db('smartbot_whatsapp_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({bot_id:botId,inbox_id:inbox&&inbox.id,direction:'inbound',contact_phone:phone,contact_name:name,message:text,provider:'kapso',provider_message_id:clean(msg&&msg.id)||null,payload:raw})}).catch(()=>null)}
async function callBrain(botId,phone,text){const r=await fetch((process.env.URL||'https://smartbots.club')+'/.netlify/functions/smartbot-brain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({botId,visitorId:'wa_'+phone,channel:'whatsapp',message:text})});return r.json().catch(()=>({success:false}))}
async function sendReply(phoneNumberId,to,body){const apiKey=process.env.KAPSO_API_KEY;if(!apiKey||!phoneNumberId||!body)return null;const client=new WhatsAppClient({baseUrl:'https://api.kapso.ai/meta/whatsapp',kapsoApiKey:apiKey});return client.messages.sendText({phoneNumberId,to,body})}
exports.handler=async(ev)=>{if(ev.httpMethod!=='POST')return reply(200,{success:true});try{const expected=clean(process.env.KAPSO_WEBHOOK_TOKEN);const supplied=clean((ev.queryStringParameters&&ev.queryStringParameters.token)||'');if(expected&&supplied!==expected)return reply(401,{success:false,error:'Webhook token invalido'});const raw=JSON.parse(ev.body||'{}');const phoneNumberId=rawPhoneNumberId(raw)||clean(process.env.KAPSO_PHONE_NUMBER_ID);const cfg=await botForPhone(phoneNumberId);if(!cfg||!cfg.bot_id)return reply(200,{success:true,ignored:'numero Kapso nao associado a bot SmartBots'});const events=normalizeWebhook(raw);let handled=0;for(const m of (events.messages||[])){if(m.kapso&&m.kapso.direction==='outbound')continue;const text=messageText(m);const phone=clean(m.from||'').replace(/\D/g,'');if(!text||!phone)continue;const name=contactName(events,m);const brain=await callBrain(cfg.bot_id,phone,text);const intent=clean(brain.intent)||'duvida';const inbox=await upsertInbox(cfg.bot_id,phone,name,text,intent);await saveInbound(cfg.bot_id,inbox,phone,name,text,m,raw);if(cfg.auto_reply===true&&brain.success&&brain.reply){const sent=await sendReply(phoneNumberId,phone,brain.reply);await db('smartbot_whatsapp_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({bot_id:cfg.bot_id,inbox_id:inbox.id,direction:'outbound',contact_phone:phone,contact_name:name,message:brain.reply,provider:'kapso',provider_message_id:clean(sent&&sent.messages&&sent.messages[0]&&sent.messages[0].id)||null,payload:sent})}).catch(()=>null)}handled++}return reply(200,{success:true,handled,statuses:(events.statuses||[]).length})}catch(e){return reply(500,{success:false,error:e.message})}};
