const fetch=require('node-fetch');
const {WhatsAppClient}=require('@kapso/whatsapp-cloud-api');

const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'OPTIONS,POST'};
function reply(c,b){return{statusCode:c,headers,body:JSON.stringify(b)}}
function clean(v){return String(v||'').trim()}
function digits(v){return clean(v).replace(/\D/g,'')}
async function db(path,opt={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase nao configurado');return fetch(url+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key,...(opt.headers||{})}})}
async function auth(botId,token){const r=await db('website_bots?bot_id=eq.'+encodeURIComponent(botId)+'&client_token=eq.'+encodeURIComponent(token)+'&select=bot_id&limit=1');const a=r.ok?await r.json():[];return !!a[0]}
async function config(botId){const r=await db('smartbot_whatsapp_config?bot_id=eq.'+encodeURIComponent(botId)+'&select=*&limit=1');const a=r.ok?await r.json():[];return a[0]||null}
exports.handler=async(ev)=>{if(ev.httpMethod==='OPTIONS')return{statusCode:204,headers,body:''};if(ev.httpMethod!=='POST')return reply(405,{success:false,error:'Method Not Allowed'});try{const b=JSON.parse(ev.body||'{}');const botId=clean(b.botId),token=clean(b.clientToken),phone=digits(b.phone),message=clean(b.message);if(!botId||!token||!phone||!message)return reply(400,{success:false,error:'botId, clientToken, phone e message obrigatorios'});if(!await auth(botId,token))return reply(403,{success:false,error:'Acesso negado'});const apiKey=process.env.KAPSO_API_KEY;if(!apiKey)return reply(500,{success:false,error:'KAPSO_API_KEY nao configurada'});const cfg=await config(botId);const phoneNumberId=clean((cfg&&cfg.provider_phone_number_id)||process.env.KAPSO_PHONE_NUMBER_ID);if(!phoneNumberId)return reply(400,{success:false,error:'PHONE_NUMBER_ID da Kapso ainda nao configurado para este bot'});const client=new WhatsAppClient({baseUrl:'https://api.kapso.ai/meta/whatsapp',kapsoApiKey:apiKey});const sent=await client.messages.sendText({phoneNumberId,to:phone,body:message});const providerMessageId=clean(sent&&sent.messages&&sent.messages[0]&&sent.messages[0].id);await db('smartbot_whatsapp_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({bot_id:botId,direction:'outbound',contact_phone:phone,message,provider:'kapso',provider_message_id:providerMessageId||null,payload:sent})}).catch(()=>null);return reply(200,{success:true,provider:'kapso',messageId:providerMessageId||null,response:sent})}catch(e){return reply(500,{success:false,error:e.message})}};
