const fetch=require('node-fetch');
const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'OPTIONS,POST'};
function reply(c,b){return{statusCode:c,headers,body:JSON.stringify(b)}}
function clean(v){return String(v||'').replace(/\s+/g,' ').trim()}
async function db(path,opt={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase nao configurado');return fetch(url+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key,...(opt.headers||{})}})}
async function bot(botId){const r=await db('website_bots?bot_id=eq.'+encodeURIComponent(botId)+'&select=*&limit=1');const a=r.ok?await r.json():[];return a[0]||null}
async function know(botId){const r=await db('smartbot_knowledge?bot_id=eq.'+encodeURIComponent(botId)+'&is_active=eq.true&order=updated_at.desc&limit=3');const a=r.ok?await r.json():[];return a.map(x=>x.content).join('\n\n')}
function intent(m){m=m.toLowerCase();if(/preço|valor|orcamento|orçamento|quanto|plano/.test(m))return'orcamento';if(/agendar|agenda|marcar|horário|horario|consulta|reunião/.test(m))return'agendamento';if(/humano|atendente|pessoa|vendedor|secretaria|secretária/.test(m))return'handoff';if(/retorno|me chama|lembrar|daqui a|voltar/.test(m))return'follow_up';if(/problema|reclama|ruim|cancelar|demora/.test(m))return'satisfacao';return'duvida'}
function phone(t){const m=String(t||'').match(/(?:\+?55\s?)?(?:\(?\d{2}\)?\s?)?9?\d{4}[-\s]?\d{4}/);return m?m[0]:null}
function email(t){const m=String(t||'').match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);return m?m[0]:null}
function name(t){const m=String(t||'').match(/(?:meu nome é|me chamo|sou)\s+([a-zA-ZÀ-ÿ' ]{2,50})/i);return m?clean(m[1].split(/,|\.| e | meu | telefone| whatsapp/i)[0]):null}
function retAt(t){const s=String(t||'').toLowerCase(),d=new Date();if(/amanhã|amanha/.test(s)){d.setDate(d.getDate()+1);return d.toISOString()}let m=s.match(/daqui a (\d+) dias?/);if(m){d.setDate(d.getDate()+Number(m[1]));return d.toISOString()}m=s.match(/daqui a (\d+) meses?/);if(m){d.setMonth(d.getMonth()+Number(m[1]));return d.toISOString()}return null}
function answer(company,k,i){const base=k?('Com base nas informações da '+company+': '+k.slice(0,450)):'Sou o assistente virtual da '+company+'.';if(i==='orcamento')return base+'\n\nPosso te ajudar com orçamento. Me diga qual serviço você procura, urgência e seu melhor WhatsApp.';if(i==='agendamento')return base+'\n\nPara agendar, me envie seu nome, WhatsApp, serviço desejado e dois horários de preferência.';if(i==='handoff')return 'Claro, vou encaminhar para a equipe. Me envie nome, WhatsApp e um resumo do que precisa.';if(i==='follow_up')return 'Combinado. Me diga seu nome, WhatsApp e quando devo lembrar a equipe de te chamar.';if(i==='satisfacao')return 'Sinto muito. Vou priorizar isso para atendimento humano. Me envie nome, WhatsApp e o que aconteceu.';return base+'\n\nMe conte melhor o que você precisa. Se quiser, envie nome e WhatsApp para a equipe continuar.'}
async function convo(botId,visitorId,channel,data){let r=await db('smartbot_conversations?bot_id=eq.'+encodeURIComponent(botId)+'&visitor_id=eq.'+encodeURIComponent(visitorId)+'&limit=1');let rows=r.ok?await r.json():[];let patch={bot_id:botId,visitor_id:visitorId,channel,intent:data.intent,last_message:data.message,last_reply:data.reply,customer_name:data.name,customer_phone:data.phone,customer_email:data.email,updated_at:new Date().toISOString()};if(rows[0]){let u=await db('smartbot_conversations?id=eq.'+rows[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});return (await u.json())[0]}let c=await db('smartbot_conversations',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});return (await c.json())[0]}
async function msg(conversation,botId,visitorId,role,content,intent){return db('smartbot_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({conversation_id:conversation.id,bot_id:botId,visitor_id:visitorId,role,content,intent})}).catch(()=>null)}
async function lead(botId,channel,m,i,n,p,e){if(!(n||p||e||['orcamento','agendamento','handoff','follow_up','satisfacao'].includes(i)))return null;let ra=retAt(m);let st=i==='follow_up'&&ra?'retorno_futuro':'novo';let r=await db('smartbot_leads',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({bot_id:botId,source_channel:channel,name:n,phone:p,email:e,intent:i,interest:m.slice(0,700),pipeline_status:st,return_at:ra,lead_temperature:['orcamento','agendamento','handoff','satisfacao'].includes(i)?'hot':'warm',created_at:new Date().toISOString()})}).catch(()=>null);if(!r||!r.ok)return null;return (await r.json())[0]}
async function event(botId,cid,lid,type,payload){return db('smartbot_automation_events',{method:'POST',headers:{Prefer:'return:minimal'},body:JSON.stringify({bot_id:botId,conversation_id:cid,lead_id:lid,event_type:type,payload})}).catch(()=>null)}
exports.handler=async(ev)=>{if(ev.httpMethod==='OPTIONS')return{statusCode:204,headers,body:''};if(ev.httpMethod!=='POST')return reply(405,{success:false,error:'Method Not Allowed'});try{const b=JSON.parse(ev.body||'{}');const botId=clean(b.botId||b.bot_id),message=clean(b.message),visitorId=clean(b.visitorId||b.visitor_id||('v_'+Date.now())),channel=clean(b.channel||'site');if(!botId||!message)return reply(400,{success:false,error:'botId e message obrigatorios'});const bt=await bot(botId);if(!bt)return reply(404,{success:false,error:'Bot nao encontrado'});const k=await know(botId);const i=intent(message);const n=name(message),p=phone(message),e=email(message);const rep=answer(bt.company_name||'empresa',k||bt.knowledge_text||bt.business_description||'',i);const c=await convo(botId,visitorId,channel,{intent:i,message,reply:rep,name:n,phone:p,email:e});await msg(c,botId,visitorId,'user',message,i);await msg(c,botId,visitorId,'assistant',rep,i);const l=await lead(botId,channel,message,i,n,p,e);if(l)await event(botId,c.id,l.id,'lead_created',{intent:i});if(i==='handoff')await event(botId,c.id,l&&l.id,'human_requested',{message});if(i==='agendamento')await event(botId,c.id,l&&l.id,'schedule_requested',{message});if(i==='follow_up')await event(botId,c.id,l&&l.id,'followup_requested',{message});return reply(200,{success:true,reply:rep,intent:i,visitorId,conversationId:c.id,leadSaved:!!l})}catch(e){return reply(500,{success:false,error:e.message})}};
