const fetch=require('node-fetch');
const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'OPTIONS,POST'};
function reply(c,b){return{statusCode:c,headers,body:JSON.stringify(b)}}
function clean(v){return String(v||'').trim()}
function amount(p){if(p==='Essencial')return 4900;if(p==='Premium')return 14900;return 7900}
function end30(){return new Date(Date.now()+30*24*60*60*1000).toISOString()}
async function sb(path,opt={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase nao configurado.');return fetch(url+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key,...(opt.headers||{})}})}
function isAdmin(t){const a=process.env.SMARTBOTS_ADMIN_TOKEN||process.env.ADMIN_TOKEN;return a&&t&&t===a}
exports.handler=async(event)=>{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers,body:''};if(event.httpMethod!=='POST')return reply(405,{success:false,error:'Method Not Allowed'});try{const b=JSON.parse(event.body||'{}');if(!isAdmin(clean(b.adminToken)))return reply(403,{success:false,error:'Admin token invalido.'});const action=clean(b.action||'upsert');const botId=clean(b.botId);if(!botId)return reply(400,{success:false,error:'botId obrigatorio.'});if(action==='get'){const r=await sb('smartbot_subscriptions?bot_id=eq.'+encodeURIComponent(botId)+'&order=created_at.desc&limit=1');return reply(200,{success:true,items:r.ok?await r.json():[]})}const plan=clean(b.plan)||'Profissional';const status=clean(b.status)||'active';let patch={bot_id:botId,plan,status,amount_cents:amount(plan),billing_cycle:'monthly',updated_at:new Date().toISOString()};if(b.companyName)patch.company_name=clean(b.companyName);if(b.email)patch.customer_email=clean(b.email);if(b.notes!==undefined)patch.notes=clean(b.notes);if(status==='active'){patch.paid_at=new Date().toISOString();patch.current_period_start=new Date().toISOString();patch.current_period_end=end30()}if(status==='canceled')patch.canceled_at=new Date().toISOString();const q='smartbot_subscriptions?bot_id=eq.'+encodeURIComponent(botId)+'&limit=1';const ex=await sb(q);const rows=ex.ok?await ex.json():[];let r;if(rows.length){r=await sb('smartbot_subscriptions?id=eq.'+encodeURIComponent(rows[0].id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)})}else{r=await sb('smartbot_subscriptions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)})}if(!r.ok)throw new Error(await r.text());return reply(200,{success:true,subscription:(await r.json())[0]})}catch(e){return reply(500,{success:false,error:e.message})}};
