const fetch=require('node-fetch');
const {timingSafeEqual}=require('crypto');
const {validateAdminSession}=require('./smartbots-admin-auth');

const headers={'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, X-Admin-Session, X-Admin-Key','Access-Control-Allow-Methods':'OPTIONS,POST'};
function reply(c,b){return{statusCode:c,headers,body:JSON.stringify(b)}}
function clean(v,m=2000){return String(v||'').trim().slice(0,m)}
function end30(){return new Date(Date.now()+30*24*60*60*1000).toISOString()}
function safeEqual(a,b){if(!a||!b)return false;const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&timingSafeEqual(x,y)}
async function sb(path,opt={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase service role nao configurado.');return fetch(url+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key,...(opt.headers||{})}})}
async function rows(r,label){if(!r.ok)throw new Error(label+': '+(await r.text()).slice(0,500));const raw=await r.text();return raw?JSON.parse(raw):[]}
async function authorized(event,b){const session=clean((event.headers&&(event.headers['x-admin-session']||event.headers['X-Admin-Session']))||b.sessionToken,300);if(session&&await validateAdminSession(session))return true;const legacy=clean((event.headers&&(event.headers['x-admin-key']||event.headers['X-Admin-Key']))||b.adminToken,500),expected=process.env.SMARTBOTS_ADMIN_TOKEN||process.env.ADMIN_TOKEN;return Boolean(expected&&legacy&&safeEqual(legacy,expected))}
function nullableLimit(value){if(value===undefined||value===null||value==='')return null;const n=Number(value);if(!Number.isSafeInteger(n)||n<0)throw new Error('Limite comercial invalido.');return n}
function planCode(label){return clean(label,100).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||'custom'}
function amountMinor(value){if(value===undefined||value===null||value==='')return null;const n=Number(String(value).replace(',','.'));if(!Number.isFinite(n)||n<0)throw new Error('Preco mensal invalido.');return Math.round(n*100)}
async function commercial(botId){const r=await sb('smartbot_commercial_settings?bot_id=eq.'+encodeURIComponent(botId)+'&select=*&limit=1');return r.ok?(await r.json())[0]||null:null}
async function bot(botId){const r=await sb('website_bots?bot_id=eq.'+encodeURIComponent(botId)+'&select=bot_id,company_name,owner_email,status&limit=1');return r.ok?(await r.json())[0]||null:null}
async function syncCommercial(botId,plan,status,monthlyPriceMinor,b){const current=await commercial(botId);const payload={bot_id:botId,plan_code:planCode(plan),plan_label:plan,commercial_status:status,monthly_price_minor:monthlyPriceMinor===undefined?(current?.monthly_price_minor??null):monthlyPriceMinor,price_currency:clean(b.currency||current?.price_currency||'BRL',12).toUpperCase(),ai_response_soft_limit:b.aiResponseSoftLimit===undefined?current?.ai_response_soft_limit??null:nullableLimit(b.aiResponseSoftLimit),whatsapp_message_soft_limit:b.whatsappMessageSoftLimit===undefined?current?.whatsapp_message_soft_limit??null:nullableLimit(b.whatsappMessageSoftLimit),total_token_soft_limit:b.totalTokenSoftLimit===undefined?current?.total_token_soft_limit??null:nullableLimit(b.totalTokenSoftLimit),warning_threshold_percent:Math.max(1,Math.min(100,Number(b.warningThresholdPercent??current?.warning_threshold_percent??80))),hard_enforcement:b.hardEnforcement===undefined?Boolean(current?.hard_enforcement):Boolean(b.hardEnforcement),notes:clean(b.commercialNotes??current?.notes??'',4000)||null,updated_at:new Date().toISOString()};const r=await sb('smartbot_commercial_settings?on_conflict=bot_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload)});return(await rows(r,'Sincronizar perfil comercial'))[0]||payload}
exports.handler=async(event)=>{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers,body:''};if(event.httpMethod!=='POST')return reply(405,{success:false,error:'Method Not Allowed'});try{const b=JSON.parse(event.body||'{}');if(!(await authorized(event,b)))return reply(401,{success:false,error:'Sessao administrativa invalida ou expirada.'});const action=clean(b.action||'upsert',50),botId=clean(b.botId,160);if(!botId)return reply(400,{success:false,error:'botId obrigatorio.'});const botData=await bot(botId);if(!botData)return reply(404,{success:false,error:'SmartBot nao encontrado.'});if(action==='get'){const [subR,commercialData]=await Promise.all([sb('smartbot_subscriptions?bot_id=eq.'+encodeURIComponent(botId)+'&order=created_at.desc&limit=1'),commercial(botId)]);return reply(200,{success:true,bot:botData,items:subR.ok?await subR.json():[],commercial:commercialData})}if(action!=='upsert')return reply(422,{success:false,error:'Acao invalida.'});const current=await commercial(botId),plan=clean(b.plan||current?.plan_label||'Piloto',100),status=clean(b.status||current?.commercial_status||'trial',60),monthlyPrice=amountMinor(b.monthlyPrice),monthlyPriceMinor=monthlyPrice===null?(current?.monthly_price_minor??null):monthlyPrice,now=new Date().toISOString();const patch={bot_id:botId,plan,status,amount_cents:monthlyPriceMinor||0,billing_cycle:'monthly',updated_at:now,company_name:clean(b.companyName||botData.company_name,300),customer_email:clean(b.email||botData.owner_email||'',320)||null,notes:clean(b.notes,4000)||null};if(status==='active'){patch.paid_at=now;patch.current_period_start=now;patch.current_period_end=end30()}if(status==='canceled')patch.canceled_at=now;const ex=await sb('smartbot_subscriptions?bot_id=eq.'+encodeURIComponent(botId)+'&limit=1');const existing=ex.ok?await ex.json():[];let r;if(existing.length)r=await sb('smartbot_subscriptions?id=eq.'+encodeURIComponent(existing[0].id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});else r=await sb('smartbot_subscriptions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});const subscription=(await rows(r,'Salvar assinatura'))[0];const commercialData=await syncCommercial(botId,plan,status,monthlyPriceMinor,b);return reply(200,{success:true,bot:botData,subscription,commercial:commercialData})}catch(e){console.error('[SubscriptionAdmin]',e.message);return reply(500,{success:false,error:e.message||'Falha ao salvar plano.'})}};
