const fetch=require('node-fetch');
const {timingSafeEqual}=require('crypto');
const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'OPTIONS,POST'};
function reply(c,b){return{statusCode:c,headers,body:JSON.stringify(b)}}
function clean(v,m=2000){return String(v||'').trim().slice(0,m)}
function legacyAmount(plan){if(plan==='Essencial')return 4900;if(plan==='Premium')return 14900;return 7900}
function end30(){return new Date(Date.now()+30*24*60*60*1000).toISOString()}
function safeEqual(a,b){if(!a||!b)return false;const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&timingSafeEqual(x,y)}
async function sb(path,opt={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw new Error('Supabase service nao configurado.');return fetch(url+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key,...(opt.headers||{})}})}
async function rows(r,label){if(!r.ok)throw new Error(label+': '+(await r.text()).slice(0,500));const raw=await r.text();return raw?JSON.parse(raw):[]}
function isAdmin(token){const expected=process.env.SMARTBOTS_ADMIN_TOKEN||process.env.ADMIN_TOKEN;return safeEqual(token,expected)}
function nullableLimit(value){if(value===undefined||value===null||value==='')return null;const n=Number(value);if(!Number.isSafeInteger(n)||n<0)throw new Error('Limite comercial invalido.');return n}
function planCode(label){return clean(label,100).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||'custom'}
async function commercial(botId){const r=await sb('smartbot_commercial_settings?bot_id=eq.'+encodeURIComponent(botId)+'&select=*&limit=1');return r.ok?(await r.json())[0]||null:null}
async function syncCommercial(botId,plan,status,amountCents,b){const current=await commercial(botId);const payload={bot_id:botId,plan_code:planCode(plan),plan_label:plan,commercial_status:status,monthly_price_minor:amountCents,price_currency:clean(b.currency||current?.price_currency||'BRL',12),ai_response_soft_limit:b.aiResponseSoftLimit===undefined?current?.ai_response_soft_limit??null:nullableLimit(b.aiResponseSoftLimit),whatsapp_message_soft_limit:b.whatsappMessageSoftLimit===undefined?current?.whatsapp_message_soft_limit??null:nullableLimit(b.whatsappMessageSoftLimit),total_token_soft_limit:b.totalTokenSoftLimit===undefined?current?.total_token_soft_limit??null:nullableLimit(b.totalTokenSoftLimit),warning_threshold_percent:Math.max(1,Math.min(100,Number(b.warningThresholdPercent??current?.warning_threshold_percent??80))),hard_enforcement:b.hardEnforcement===undefined?Boolean(current?.hard_enforcement):Boolean(b.hardEnforcement),notes:clean(b.commercialNotes??current?.notes??'',4000)||null,updated_at:new Date().toISOString()};const r=await sb('smartbot_commercial_settings?on_conflict=bot_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload)});return (await rows(r,'Sincronizar perfil comercial'))[0]||payload}
exports.handler=async(event)=>{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers,body:''};if(event.httpMethod!=='POST')return reply(405,{success:false,error:'Method Not Allowed'});try{const b=JSON.parse(event.body||'{}');if(!isAdmin(clean(b.adminToken,500)))return reply(403,{success:false,error:'Admin token invalido.'});const action=clean(b.action||'upsert',50);const botId=clean(b.botId,160);if(!botId)return reply(400,{success:false,error:'botId obrigatorio.'});if(action==='get'){const [subR,commercialData]=await Promise.all([sb('smartbot_subscriptions?bot_id=eq.'+encodeURIComponent(botId)+'&order=created_at.desc&limit=1'),commercial(botId)]);return reply(200,{success:true,items:subR.ok?await subR.json():[],commercial:commercialData})}const plan=clean(b.plan||'Profissional',100),status=clean(b.status||'active',60);const amountCents=b.amountCents===undefined?legacyAmount(plan):Math.max(0,Math.round(Number(b.amountCents)||0));const now=new Date().toISOString();let patch={bot_id:botId,plan,status,amount_cents:amountCents,billing_cycle:'monthly',updated_at:now};if(b.companyName)patch.company_name=clean(b.companyName,300);if(b.email)patch.customer_email=clean(b.email,320);if(b.notes!==undefined)patch.notes=clean(b.notes,4000);if(status==='active'){patch.paid_at=now;patch.current_period_start=now;patch.current_period_end=end30()}if(status==='canceled')patch.canceled_at=now;const ex=await sb('smartbot_subscriptions?bot_id=eq.'+encodeURIComponent(botId)+'&limit=1');const existing=ex.ok?await ex.json():[];let r;if(existing.length)r=await sb('smartbot_subscriptions?id=eq.'+encodeURIComponent(existing[0].id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});else r=await sb('smartbot_subscriptions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});const subscription=(await rows(r,'Salvar assinatura'))[0];const commercialData=await syncCommercial(botId,plan,status,amountCents,b);return reply(200,{success:true,subscription,commercial:commercialData})}catch(e){console.error('subscription-admin',e);return reply(500,{success:false,error:e.message})}};
