const fetch=require('node-fetch');
const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*'};
function reply(c,b){return{statusCode:c,headers,body:JSON.stringify(b)}}
function clean(v){return String(v||'').trim()}
async function db(path,opt={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase nao configurado');return fetch(url+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+key,...(opt.headers||{})}})}
function parse(body){const p=body||{};const phone=clean(p.phone||p.from||p.sender||p.senderPhone||p.From||p.data&&p.data.phone||p.message&&p.message.from);const name=clean(p.senderName||p.name||p.pushName||p.ProfileName||p.data&&p.data.senderName);const text=clean(p.text||p.body||p.Body||p.message||p.data&&p.data.text||p.data&&p.data.body||p.message&&p.message.text);const botId=clean(p.botId||p.instanceId||p.instance||p.data&&p.data.instanceId||process.env.WHATSAPP_DEFAULT_BOT_ID);const provider=clean(p.provider||p.type||'webhook');return{botId,phone,name,text,provider}}
function intent(m){m=String(m||'').toLowerCase();if(/preço|valor|orçamento|orcamento|quanto/.test(m))return'orcamento';if(/agenda|agendar|marcar|horário|horario|consulta/.test(m))return'agendamento';if(/humano|atendente|pessoa|vendedor/.test(m))return'handoff';if(/retorno|me chama|lembrar|voltar/.test(m))return'follow_up';return'duvida'}
async function upsertInbox(x,i){const r=await db('smartbot_whatsapp_inbox?bot_id=eq.'+encodeURIComponent(x.botId)+'&contact_phone=eq.'+encodeURIComponent(x.phone)+'&limit=1');const rows=r.ok?await r.json():[];const patch={bot_id:x.botId,contact_phone:x.phone,contact_name:x.name,last_message:x.text,intent:i,status:'new',source:'whatsapp',updated_at:new Date().toISOString()};let w;if(rows[0])w=await db('smartbot_whatsapp_inbox?id=eq.'+rows[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});else w=await db('smartbot_whatsapp_inbox',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});if(!w.ok)throw new Error(await w.text());return (await w.json())[0]}
exports.handler=async(ev)=>{try{const body=JSON.parse(ev.body||'{}');const x=parse(body);if(!x.botId||!x.text)return reply(200,{success:true,ignored:'missing botId or text'});const i=intent(x.text);const inbox=await upsertInbox(x,i);await db('smartbot_whatsapp_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({bot_id:x.botId,inbox_id:inbox.id,direction:'inbound',contact_phone:x.phone,contact_name:x.name,message:x.text,provider:x.provider,payload:body})}).catch(()=>null);try{await fetch((process.env.URL||'https://smartbots.club')+'/.netlify/functions/smartbot-brain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({botId:x.botId,visitorId:'wa_'+x.phone,channel:'whatsapp',message:x.text})})}catch(e){}return reply(200,{success:true,inboxId:inbox.id,intent:i})}catch(e){return reply(500,{success:false,error:e.message})}};
