let currentMessage='';
function S(){try{return JSON.parse(localStorage.getItem('sb_session')||'{}')}catch(e){return {}}}
function E(v){return String(v||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function D(v){return String(v||'').replace(/\D/g,'')}
function WA(p,m){let n=D(p);if(!n)return '#';if(!n.startsWith('55')&&n.length>=10)n='55'+n;return 'https://wa.me/'+n+'?text='+encodeURIComponent(m)}
function msg(t,c){c=c||'sua empresa';if(t==='confirmacao')return 'Oi, tudo bem? Aqui é da '+c+'. Passando para confirmar seu horário. Está tudo certo?';if(t==='retorno')return 'Oi, tudo bem? Aqui é da '+c+'. Estou passando para lembrar do seu retorno. Quer ver um horário?';if(t==='orcamento')return 'Oi, tudo bem? Aqui é da '+c+'. Vi que você pediu informações. Ainda faz sentido conversarmos?';if(t==='indicacao')return 'Oi, tudo bem? Aqui é da '+c+'. Você conhece alguém que também poderia precisar da nossa ajuda?';if(t==='pos_atendimento')return 'Oi, tudo bem? Aqui é da '+c+'. Queríamos saber se deu tudo certo com seu atendimento.';return 'Oi, tudo bem? Aqui é da '+c+'. Temos uma condição especial para clientes antigos. Quer saber mais?'}
function ok(t,x){let s=x.pipeline_status||'',i=x.intent||'',a=String(x.interest||'').toLowerCase();if(t==='confirmacao')return s==='agendado'||i==='agendamento';if(t==='retorno')return s==='retorno_futuro';if(t==='orcamento')return i==='orcamento'||a.includes('orçamento')||a.includes('orcamento');if(t==='indicacao'||t==='pos_atendimento')return s==='executado';return s==='reativacao'||x.origin==='importado'||i==='reativacao'}
async function contacts(t,m){let s=S();let r=await fetch('/.netlify/functions/opportunities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'list',botId:s.botId,clientToken:s.clientToken})});let j=await r.json();let arr=(j.leads||[]).filter(x=>ok(t,x)).slice(0,80);if(!arr.length)return '<p class="text-gray-500 text-sm">Nenhum contato encontrado para esta ação.</p>';return arr.map(x=>'<div class="border-b border-white/10 py-3"><b class="text-white">'+E(x.name||x.phone||'Contato')+'</b><p class="text-sm text-gray-400">'+E(x.interest||'')+'</p><div class="flex gap-2 mt-2"><a target="_blank" class="bg-green-400 text-black px-3 py-2 rounded-lg text-xs font-black" href="'+WA(x.phone,m)+'">Abrir WhatsApp</a><button class="bg-white/10 px-3 py-2 rounded-lg text-xs" onclick="navigator.clipboard.writeText(currentMessage)">Copiar</button></div></div>').join('')}
async function createCampaign(type){let s=S();if(!s.botId){result.textContent='Entre pelo painel primeiro.';return}result.textContent='Preparando...';currentMessage=msg(type,s.companyName);let list=await contacts(type,currentMessage);result.innerHTML='<div class="space-y-4"><b class="text-white">Mensagem sugerida</b><textarea id="msg" oninput="currentMessage=this.value" class="w-full h-32 bg-slate-900 border border-white/10 rounded-xl p-3 text-white">'+E(currentMessage)+'</textarea><button onclick="navigator.clipboard.writeText(currentMessage)" class="bg-green-400 text-black px-4 py-2 rounded-xl font-black">Copiar mensagem geral</button><h3 class="font-black text-white mt-4">Contatos sugeridos</h3>'+list+'</div>'}
