var catalogItems=[];
function el(id){return document.getElementById(id)}
function session(){try{return JSON.parse(sessionStorage.getItem('sb_client_session')||localStorage.getItem('sb_session')||'{}')}catch(_){return{}}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function fmtPrice(v,c){if(v===null||v===undefined||v==='')return'';try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:c||'BRL'}).format(Number(v))}catch(_){return(c||'BRL')+' '+v}}
async function api(body){var s=session();if(!s.botId||!s.clientToken)throw new Error('Sessão do cliente não encontrada. Entre pelo Painel.');var r=await fetch('/.netlify/functions/catalog-manager',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,botId:s.botId,clientToken:s.clientToken})}),j={};try{j=await r.json()}catch(_){}if(!r.ok||j.success===false)throw new Error(j.error||'Falha no catálogo.');return j}
function attrsToText(a){if(!a||typeof a!=='object')return'';return Object.keys(a).map(function(k){return k+': '+a[k]}).join('\n')}
function textToAttrs(v){var out={};String(v||'').split(/\r?\n/).forEach(function(line){var i=line.indexOf(':');if(i>0){var k=line.slice(0,i).trim(),val=line.slice(i+1).trim();if(k&&val)out[k]=val}});return out}
function render(){el('count').textContent=catalogItems.length+' item(ns)';el('items').innerHTML=catalogItems.map(function(x){var avail=x.availability_status||'available',status={available:'Disponível',on_request:'Sob consulta',unavailable:'Indisponível',sold_out:'Esgotado/vendido',paused:'Pausado'}[avail]||avail;return '<div class="item"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><div style="font-size:17px;font-weight:900">'+esc(x.name)+'</div><div class="help">'+esc(x.category||x.item_type||'')+'</div></div><div class="pill '+(avail==='available'?'on':'off')+'">'+esc(status)+'</div></div>'+(x.description?'<div style="margin-top:8px;color:#cbd5e1">'+esc(x.description)+'</div>':'')+'<div style="display:flex;gap:12px;flex-wrap:wrap;margin-top:10px"><span class="pill">'+esc(fmtPrice(x.price,x.currency))+'</span>'+(x.sku?'<span class="pill">SKU '+esc(x.sku)+'</span>':'')+(x.active===false?'<span class="pill off">inativo</span>':'')+'</div><div class="actions" style="margin-top:12px"><button class="btn btn2" onclick="openItem(\''+esc(x.id)+'\')">Editar</button><button class="btn danger" onclick="deleteItem(\''+esc(x.id)+'\')">Excluir</button></div></div>'}).join('')||'<div class="help">Nenhum item cadastrado. Adicione um item ou importe CSV.</div>'}
async function load(){try{var j=await api({action:'get'}),c=j.config||{};el('enabled').value=String(c.enabled===true);el('catalogType').value=c.catalog_type||'generic';el('displayName').value=c.display_name||'Catálogo';el('currency').value=c.currency||'BRL';el('showPrices').checked=c.show_prices!==false;el('notes').value=c.notes||'';catalogItems=j.items||[];render()}catch(e){el('items').innerHTML='<div class="help" style="color:#f87171">'+esc(e.message)+'</div>'}}
async function saveConfig(){var b=el('saveConfigBtn');b.disabled=true;el('configMsg').textContent='Salvando...';try{await api({action:'save_config',enabled:el('enabled').value==='true',catalogType:el('catalogType').value,displayName:el('displayName').value,currency:el('currency').value,showPrices:el('showPrices').checked,notes:el('notes').value});el('configMsg').textContent='Salvo e sincronizado com o Brain ✓';await load()}catch(e){el('configMsg').textContent=e.message}finally{b.disabled=false}}
function openItem(id){var x=id?catalogItems.find(function(i){return i.id===id}):null;el('modalTitle').textContent=x?'Editar item':'Novo item';el('itemId').value=x?x.id:'';el('itemName').value=x?x.name:'';el('itemCategory').value=x?(x.category||''):'';el('itemType').value=x?(x.item_type||''):({services:'serviço',products:'produto',menu:'prato',properties:'imóvel',courses:'curso',vehicles:'veículo',packages:'pacote'}[el('catalogType').value]||'item');el('itemSku').value=x?(x.sku||''):'';el('itemPrice').value=x&&x.price!=null?String(x.price).replace('.',','):'';el('itemAvailability').value=x?(x.availability_status||'available'):'available';el('itemDescription').value=x?(x.description||''):'';el('itemAttributes').value=x?attrsToText(x.attributes):'';el('itemActive').checked=!x||x.active!==false;el('itemMsg').textContent='';el('modal').classList.add('open')}
function closeItem(){el('modal').classList.remove('open')}
async function saveItem(){var b=el('saveItemBtn'),name=el('itemName').value.trim();if(!name){el('itemMsg').textContent='Informe o nome.';return}b.disabled=true;el('itemMsg').textContent='Salvando...';try{await api({action:'save_item',id:el('itemId').value||null,name:name,category:el('itemCategory').value,itemType:el('itemType').value,sku:el('itemSku').value,price:el('itemPrice').value,currency:el('currency').value,availabilityStatus:el('itemAvailability').value,description:el('itemDescription').value,attributes:textToAttrs(el('itemAttributes').value),active:el('itemActive').checked});closeItem();await load()}catch(e){el('itemMsg').textContent=e.message}finally{b.disabled=false}}
async function deleteItem(id){if(!confirm('Excluir este item do catálogo?'))return;try{await api({action:'delete_item',id:id});await load()}catch(e){alert(e.message)}}
function parseCsv(text){var lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/).filter(function(x){return x.trim()});if(lines.length<2)return[];function row(line){var out=[],cur='',q=false;for(var i=0;i<line.length;i++){var ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out}var head=row(lines[0]).map(function(x){return x.toLowerCase().trim()});return lines.slice(1).map(function(line){var vals=row(line),o={};head.forEach(function(h,i){o[h]=vals[i]||''});return{name:o.name||o.nome,category:o.category||o.categoria,description:o.description||o.descricao,price:o.price||o.preco,availabilityStatus:o.availability_status||o.disponibilidade||'available',itemType:o.item_type||o.tipo||'item',sku:o.sku||o.codigo||'',currency:el('currency').value,active:true}}).filter(function(x){return x.name})}
async function importCsv(input){var f=input.files&&input.files[0];if(!f)return;try{var items=parseCsv(await f.text());if(!items.length)throw new Error('CSV sem itens válidos.');if(items.length>300)items=items.slice(0,300);var j=await api({action:'bulk_import',items:items});alert(j.imported+' item(ns) importados e sincronizados com o Brain.');await load()}catch(e){alert(e.message)}finally{input.value=''}}
window.addEventListener('load',load);
