function getS(){try{return JSON.parse(localStorage.getItem('sb_session')||'{}')}catch(e){return {}}}
function safe(v){return String(v||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
async function req(body){var s=getS();var r=await fetch('/.netlify/functions/opportunities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({botId:s.botId,clientToken:s.clientToken,action:body.action})});return r.json()}
async function reqAppt(){var s=getS();var r=await fetch('/.netlify/functions/appts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({botId:s.botId,clientToken:s.clientToken,action:'list'})});return r.json()}
function mini(title,n,href){return '<a href="'+href+'" class="bg-white/5 border border-white/10 rounded-xl p-3 block hover:border-green-400"><div class="text-2xl font-black">'+n+'</div><div class="text-xs text-gray-400">'+safe(title)+'</div></a>'}
function msgLink(x,t){var p=x.phone||x.customer_phone||'';return '/whatsapp.html?p='+encodeURIComponent(p)+'&t='+encodeURIComponent(t||'orcamento')}
function line(x,t){return '<div class="bg-slate-950 border border-white/10 rounded-xl p-3 mb-2"><b>'+safe(x.name||x.customer_name||x.phone||x.customer_phone||x.email||'Contato')+'</b><p class="text-sm text-gray-400">'+safe(x.interest||x.service_name||x.owner_notes||x.notes||'')+'</p><div class="flex gap-2 mt-2"><a href="/crm.html" class="bg-white/10 px-3 py-2 rounded-lg text-xs">CRM</a><a href="'+msgLink(x,t)+'" class="bg-green-400 text-black px-3 py-2 rounded-lg text-xs font-black">Mensagem</a></div></div>'}
function block(title,arr,t){return '<div class="bg-slate-900 border border-white/10 rounded-2xl p-4"><h2 class="font-black text-xl">'+safe(title)+' <span class="text-gray-500">'+arr.length+'</span></h2><div class="mt-3">'+(arr.length?arr.slice(0,10).map(function(x){return line(x,t)}).join(''):'<p class="text-gray-600 text-sm">Nada para agora.</p>')+'</div></div>'}
function soon(v){if(!v)return false;var d=new Date(v).getTime(),n=Date.now();return d>n-43200000&&d<n+172800000}
async function loadToday(){var b=document.getElementById('board'),s=document.getElementById('summary'),st=getS();if(!st.botId){b.innerHTML='<p class="text-yellow-300">Entre pelo painel primeiro.</p>';return}b.innerHTML='<p class="text-gray-500">Carregando...</p>';try{var data=await req({action:'list'});var leads=data.leads||[];var agenda=[];try{agenda=(await reqAppt()).items||[]}catch(e){}var conf=agenda.filter(function(x){return soon(x.appointment_at)});var ret=leads.filter(function(x){return (x.pipeline_status||'')==='retorno_futuro'});var rea=leads.filter(function(x){return (x.pipeline_status||'')==='reativacao'});var con=leads.filter(function(x){return (x.pipeline_status||'')==='contatado'});var exe=leads.filter(function(x){return (x.pipeline_status||'')==='executado'});var per=leads.filter(function(x){return (x.pipeline_status||'')==='perdido'});s.innerHTML=mini('Confirmar horários',conf.length,'/agenda.html')+mini('Retornos',ret.length,'/crm.html')+mini('Reativação',rea.length,'/crm.html')+mini('Contatados',con.length,'/crm.html')+mini('Indicações',exe.length,'/crm.html')+mini('Recuperar',per.length,'/crm.html');b.innerHTML=block('Confirmar horários',conf,'agendamento')+block('Retornos para hoje',ret,'retorno')+block('Clientes para reativar',rea,'reativacao')+block('Contatados para acompanhar',con,'orcamento')+block('Clientes atendidos para indicação',exe,'indicacao')+block('Clientes perdidos para recuperar',per,'reativacao')}catch(e){b.innerHTML='<p class="text-red-400">Erro: '+safe(e.message)+'</p>'}}
document.addEventListener('DOMContentLoaded',loadToday);
document.addEventListener('DOMContentLoaded',function(){var s=document.createElement('script');s.src='/hoje-campanhas.js';document.body.appendChild(s)});
