(function(){
var state={site:null,visitor:'ms_'+Date.now()+'_'+Math.random().toString(36).slice(2)};
function el(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function slug(){var p=location.pathname.split('/').filter(Boolean);return p[0]==='s'?(p[1]||''):new URLSearchParams(location.search).get('slug')||''}
function setTheme(s){document.documentElement.style.setProperty('--accent',s.accentColor||'#00ff88');document.body.classList.remove('theme-light','theme-ocean','theme-warm');if(s.theme==='light')document.body.classList.add('theme-light');if(s.theme==='ocean')document.body.classList.add('theme-ocean');if(s.theme==='warm')document.body.classList.add('theme-warm')}
function meta(name,value,prop){if(!value)return;var q=prop?'meta[property="'+name+'"]':'meta[name="'+name+'"]',m=document.querySelector(q);if(!m){m=document.createElement('meta');m.setAttribute(prop?'property':'name',name);document.head.appendChild(m)}m.content=value}
function applySeo(s){var seo=s.seo||{};document.title=seo.title||s.title||s.companyName||'Atendimento';meta('description',seo.description||s.subtitle||'');meta('og:title',seo.title||s.title||'',true);meta('og:description',seo.description||s.subtitle||'',true)}
function primary(){var s=state.site;if(!s)return;if(s.primaryCtaKind==='chat'||!s.primaryCtaUrl){openChat();return}window.open(s.primaryCtaUrl,'_blank','noopener,noreferrer')}
function addBubble(text,user){var b=document.createElement('div');b.className='bubble '+(user?'user':'bot');b.textContent=text;el('chatLog').appendChild(b);el('chatLog').scrollTop=el('chatLog').scrollHeight;return b}
function openChat(){el('chatPanel').classList.add('open');if(!el('chatLog').children.length)addBubble('Olá! Sou o atendimento inteligente da '+state.site.companyName+'. Como posso ajudar?',false);setTimeout(function(){el('chatInput').focus()},50)}
function closeChat(){el('chatPanel').classList.remove('open')}
async function send(message){message=String(message||'').trim();if(!message||!state.site)return;addBubble(message,true);var wait=addBubble('Pensando…',false);try{var r=await fetch('/.netlify/functions/smartbot-brain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({botId:state.site.botId,visitorId:state.visitor,channel:'minisite',message:message})});var j=await r.json().catch(function(){return{}});wait.textContent=j.reply||j.error||'Não consegui responder agora. Tente novamente.'}catch(_){wait.textContent='Não consegui responder agora. Tente novamente.'}}
function renderSections(sections){var root=el('dynamicSections');root.innerHTML='';(sections||[]).forEach(function(sec){var wrap=document.createElement('section');wrap.className='wrap section';var head='<div class="section-head"><h2>'+esc(sec.title||'')+'</h2>'+(sec.text?'<p class="section-lead">'+esc(sec.text)+'</p>':'')+'</div>';var items=Array.isArray(sec.items)?sec.items:[];if(sec.type==='cards'&&items.length){wrap.innerHTML=head+'<div class="grid">'+items.map(function(i){return'<article class="card">'+(i.badge?'<div class="badge">'+esc(i.badge)+'</div>':'')+'<h3>'+esc(i.title||'')+'</h3><p>'+esc(i.text||'')+'</p>'+(i.price?'<div class="price">'+esc(i.price)+'</div>':'')+'</article>'}).join('')+'</div>'}else if(sec.type==='steps'&&items.length){wrap.innerHTML=head+'<div class="grid">'+items.map(function(i,n){return'<article class="card"><div class="badge">0'+(n+1)+'</div><h3>'+esc(i.title||'')+'</h3><p>'+esc(i.text||'')+'</p></article>'}).join('')+'</div>'}else{wrap.innerHTML=head+(items.length?'<div class="grid">'+items.map(function(i){return'<article class="card"><h3>'+esc(i.title||'')+'</h3><p>'+esc(i.text||'')+'</p></article>'}).join('')+'</div>':'')}root.appendChild(wrap)})}
function renderFaq(faq){var list=Array.isArray(faq)?faq:[],section=el('faqSection');if(!list.length){section.style.display='none';return}el('faq').innerHTML=list.map(function(x){return'<details><summary>'+esc(x.question)+'</summary><p>'+esc(x.answer)+'</p></details>'}).join('')}
function render(s){state.site=s;setTheme(s);applySeo(s);el('brandName').textContent=s.companyName||s.title;if(s.logoUrl){el('brandLogo').src=s.logoUrl;el('brandLogo').style.display='block';el('brandDot').style.display='none'}el('eyebrow').textContent=s.eyebrow||'Atendimento inteligente';el('title').textContent=s.title||s.companyName;el('subtitle').textContent=s.subtitle||'';el('heroCompany').textContent=s.companyName||s.title;if(s.heroImageUrl){el('heroImage').src=s.heroImageUrl;el('heroImage').style.display='block'}var about=String(s.aboutText||'').trim();if(about){el('aboutTitle').textContent=s.aboutTitle||'Sobre';el('aboutText').textContent=about}else el('aboutSection').style.display='none';document.querySelectorAll('[data-primary]').forEach(function(b){b.textContent=s.primaryCtaLabel||'Falar agora';b.addEventListener('click',primary)});if(s.secondaryCtaUrl&&s.secondaryCtaLabel){['navSecondary','heroSecondary'].forEach(function(id){var a=el(id);a.href=s.secondaryCtaUrl;a.textContent=s.secondaryCtaLabel;a.style.display='inline-flex'})}renderSections(s.sections);renderFaq(s.faq);var c=s.contact||{},contacts=[];if(c.email)contacts.push(c.email);if(c.website)contacts.push(c.website);el('footerContact').textContent=contacts.join(' · ');el('chatTitle').textContent=s.companyName||'Atendimento';el('chatFab').textContent='💬 '+(s.primaryCtaKind==='chat'?(s.primaryCtaLabel||'Falar agora'):'Falar com o SmartBot');el('loading').style.display='none';el('app').style.display='block'}
async function load(){var s=slug();if(!s){el('loading').style.display='none';el('errorBox').style.display='block';return}try{var r=await fetch('/.netlify/functions/minisite-public',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug:s})});var j=await r.json().catch(function(){return{}});if(!r.ok||!j.success)throw new Error(j.error||'Não encontrado');render(j.site)}catch(_){el('loading').style.display='none';el('errorBox').style.display='block'}}
el('chatFab').addEventListener('click',openChat);el('chatClose').addEventListener('click',closeChat);el('chatForm').addEventListener('submit',function(e){e.preventDefault();var m=el('chatInput').value;el('chatInput').value='';send(m)});load()
})();