var state={portalToken:null,site:null};
function el(id){return document.getElementById(id)}
function session(){try{return JSON.parse(sessionStorage.getItem('sb_client_session')||'{}')}catch(_){return{}}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]})}
function setMsg(v,bad){el('msg').textContent=v||'';el('msg').style.color=bad?'#f87171':'#aab4bf'}
async function api(body){var r=await fetch('/.netlify/functions/minisite-manager',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,portalToken:state.portalToken})}),j={};try{j=await r.json()}catch(_){}if(r.status===401){sessionStorage.removeItem('sb_client_session');location.replace('/portal-login.html?next=%2Fmini-site.html');throw new Error('Sessão expirada.')}if(!r.ok||j.success===false)throw new Error(j.error||'Falha no MiniSite.');return j}
function values(){return{eyebrow:el('eyebrow').value,title:el('title').value,subtitle:el('subtitle').value,aboutTitle:el('aboutTitle').value,aboutText:el('aboutText').value,primaryCtaLabel:el('primaryCtaLabel').value,primaryCtaKind:state.site&&state.site.primaryCtaKind||'chat',primaryCtaUrl:state.site&&state.site.primaryCtaUrl||null,theme:el('theme').value,accentColor:el('accentColor').value,logoUrl:el('logoUrl').value,heroImageUrl:el('heroImageUrl').value,sections:state.site&&state.site.sections||[],faq:state.site&&state.site.faq||[],seo:state.site&&state.site.seo||{}}}
function fill(s){state.site=s||null;if(!s){el('status').textContent='Novo';el('status').className='status draft';renderPreview();renderPublish();return}el('eyebrow').value=s.eyebrow||'';el('title').value=s.title||'';el('subtitle').value=s.subtitle||'';el('aboutTitle').value=s.aboutTitle||'';el('aboutText').value=s.aboutText||'';el('primaryCtaLabel').value=s.primaryCtaLabel||'Falar agora';el('theme').value=s.theme||'aurora';el('accentColor').value=s.accentColor||'#00ff88';el('logoUrl').value=s.logoUrl||'';el('heroImageUrl').value=s.heroImageUrl||'';el('status').textContent=s.status==='published'?(s.hasUnpublishedChanges?'Publicado · alterações pendentes':'Publicado'):'Rascunho';el('status').className='status '+(s.status==='published'?'published':'draft');renderPreview();renderPublish()}
function renderPreview(){var s=state.site||values();el('previewEyebrow').textContent=el('eyebrow').value||'Atendimento inteligente';el('previewTitle').textContent=el('title').value||'Seu MiniSite';el('previewSubtitle').textContent=el('subtitle').value||'';var sections=s.sections||[];el('sectionChips').innerHTML=sections.map(function(x){return'<span class="section-chip">'+esc(x.title||x.type||'Seção')+'</span>'}).join('');el('faqCount').textContent=(s.faq||[]).length?((s.faq||[]).length+' pergunta(s) frequente(s) gerada(s)'):'';el('generatedAt').textContent=s.generatedAt?'Gerado '+new Date(s.generatedAt).toLocaleString('pt-BR'):''}
function renderPublish(){var s=state.site,published=s&&s.status==='published'&&s.publicUrl;if(published){el('publicUrl').textContent=s.publicUrl;el('openBtn').disabled=false;el('copyBtn').disabled=false;el('publishBtn').textContent=s.hasUnpublishedChanges?'Publicar alterações':'Atualizar publicação';el('unpublishBtn').style.display='inline-flex';el('qr').style.display='inline-block';el('qr').innerHTML='<img alt="QR Code" src="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data='+encodeURIComponent(s.publicUrl)+'">'}else{el('publicUrl').textContent=s&&s.slug?'Pronto para publicar: smartbots.club/s/'+s.slug:'Ainda não publicado';el('openBtn').disabled=true;el('copyBtn').disabled=true;el('publishBtn').textContent='Publicar MiniSite';el('unpublishBtn').style.display='none';el('qr').style.display='none'}}
async function load(){var s=session();if(!s.portalToken){location.replace('/portal-login.html?next=%2Fmini-site.html');return}state.portalToken=s.portalToken;try{var j=await api({action:'get'});fill(j.site)}catch(e){setMsg(e.message,true)}}
async function generateSite(){var b=el('generateBtn');b.disabled=true;b.innerHTML='<span class="spinner"></span> Gerando…';setMsg('Lendo informações da empresa e montando o MiniSite…');try{var j=await api({action:'generate'});fill(j.site);setMsg('MiniSite gerado. Revise e publique quando estiver pronto.')}catch(e){setMsg(e.message,true)}finally{b.disabled=false;b.textContent='✨ Gerar novamente'}}
async function saveSite(){var b=el('saveBtn');b.disabled=true;b.textContent='Salvando…';try{var j=await api({action:'save',...values()});fill(j.site);setMsg('Alterações salvas ✓')}catch(e){setMsg(e.message,true)}finally{b.disabled=false;b.textContent='Salvar alterações'}}
async function publishSite(){var b=el('publishBtn');b.disabled=true;b.textContent='Publicando…';try{if(!state.site){await generateSite()}await saveSite();var j=await api({action:'publish'});fill(j.site);setMsg('MiniSite publicado ✓')}catch(e){setMsg(e.message,true)}finally{b.disabled=false}}
async function unpublishSite(){if(!confirm('Tirar o MiniSite do ar? O rascunho continuará salvo.'))return;try{var j=await api({action:'unpublish'});fill(j.site);setMsg('MiniSite retirado do ar.')}catch(e){setMsg(e.message,true)}}
function openPublic(){if(state.site&&state.site.publicUrl)window.open(state.site.publicUrl,'_blank','noopener,noreferrer')}
function copyPublic(){if(!state.site||!state.site.publicUrl)return;navigator.clipboard.writeText(state.site.publicUrl).then(function(){setMsg('Link copiado ✓')})}
['eyebrow','title','subtitle','aboutTitle','aboutText','primaryCtaLabel','theme','accentColor','logoUrl','heroImageUrl'].forEach(function(id){document.getElementById(id).addEventListener('input',renderPreview)});
window.addEventListener('load',load);