-- SmartBots.club — schema mínimo esperado pelas funções Netlify
-- Rode no SQL Editor do Supabase antes de testar o onboarding.

create table if not exists website_bots (
  id bigint generated by default as identity primary key,
  bot_id text unique not null,
  client_token text not null,
  company_name text not null,
  website text,
  email text not null,
  owner_name text,
  owner_whatsapp text,
  assistant_id text,
  vector_store_id text,
  plan text default 'site',
  status text default 'pending_payment',
  payment_link text,
  payment_status text,
  payment_id text,
  created_at timestamptz default now(),
  updated_at timestamptz
);

create table if not exists whatsapp_bots (
  id bigint generated by default as identity primary key,
  bot_id text unique not null,
  client_token text,
  owner_name text,
  owner_email text not null,
  owner_whatsapp text,
  company_name text not null,
  website text,
  business_description text,
  assistant_id text,
  vector_store_id text,
  status text default 'pending_payment',
  payment_link text,
  payment_status text,
  payment_id text,
  phone_number text,
  created_at timestamptz default now(),
  updated_at timestamptz
);

create table if not exists bot_training_files (
  id bigint generated by default as identity primary key,
  bot_id text not null,
  openai_file_id text,
  file_name text,
  file_size_bytes bigint,
  status text default 'active',
  created_at timestamptz default now()
);

create table if not exists chat_history (
  id bigint generated by default as identity primary key,
  bot_id text not null,
  user_identifier text,
  user_message text,
  bot_response text,
  created_at timestamptz default now()
);

create index if not exists idx_website_bots_login on website_bots(email, client_token);
create index if not exists idx_website_bots_bot_id on website_bots(bot_id);
create index if not exists idx_whatsapp_bots_bot_id on whatsapp_bots(bot_id);
create index if not exists idx_chat_history_bot_id on chat_history(bot_id);
create index if not exists idx_training_files_bot_id on bot_training_files(bot_id);
