-- SmartBots.club — schema mínimo esperado pelas funções Netlify
-- Rode no SQL Editor do Supabase antes de testar o onboarding.
-- Este arquivo também corrige tabelas que já existiam sem todas as colunas.

create table if not exists website_bots (
  id bigint generated by default as identity primary key,
  bot_id text unique,
  client_token text,
  company_name text,
  website text,
  email text,
  owner_name text,
  owner_whatsapp text,
  business_description text,
  knowledge_text text,
  knowledge_status text,
  uploaded_file_name text,
  uploaded_file_mime text,
  uploaded_file_size_bytes bigint,
  uploaded_file_base64 text,
  assistant_id text,
  vector_store_id text,
  plan text default 'site',
  status text default 'pending_payment',
  payment_link text,
  payment_status text,
  payment_id text,
  created_at timestamptz default now(),
  updated_at timestamptz
);

alter table website_bots add column if not exists bot_id text;
alter table website_bots add column if not exists client_token text;
alter table website_bots add column if not exists company_name text;
alter table website_bots add column if not exists website text;
alter table website_bots add column if not exists email text;
alter table website_bots add column if not exists owner_name text;
alter table website_bots add column if not exists owner_whatsapp text;
alter table website_bots add column if not exists business_description text;
alter table website_bots add column if not exists knowledge_text text;
alter table website_bots add column if not exists knowledge_status text;
alter table website_bots add column if not exists uploaded_file_name text;
alter table website_bots add column if not exists uploaded_file_mime text;
alter table website_bots add column if not exists uploaded_file_size_bytes bigint;
alter table website_bots add column if not exists uploaded_file_base64 text;
alter table website_bots add column if not exists assistant_id text;
alter table website_bots add column if not exists vector_store_id text;
alter table website_bots add column if not exists plan text default 'site';
alter table website_bots add column if not exists status text default 'pending_payment';
alter table website_bots add column if not exists payment_link text;
alter table website_bots add column if not exists payment_status text;
alter table website_bots add column if not exists payment_id text;
alter table website_bots add column if not exists created_at timestamptz default now();
alter table website_bots add column if not exists updated_at timestamptz;

create unique index if not exists idx_website_bots_bot_id_unique on website_bots(bot_id);
create index if not exists idx_website_bots_login on website_bots(email, client_token);
create index if not exists idx_website_bots_bot_id on website_bots(bot_id);

create table if not exists whatsapp_bots (
  id bigint generated by default as identity primary key,
  bot_id text unique,
  client_token text,
  owner_name text,
  owner_email text,
  owner_whatsapp text,
  company_name text,
  website text,
  business_description text,
  knowledge_text text,
  knowledge_status text,
  uploaded_file_name text,
  uploaded_file_mime text,
  uploaded_file_size_bytes bigint,
  uploaded_file_base64 text,
  assistant_id text,
  vector_store_id text,
  status text default 'pending_payment',
  payment_link text,
  payment_status text,
  payment_id text,
  phone_number text,
  created_at timestamptz default now(),
  updated_at timestamptz
);

alter table whatsapp_bots add column if not exists bot_id text;
alter table whatsapp_bots add column if not exists client_token text;
alter table whatsapp_bots add column if not exists owner_name text;
alter table whatsapp_bots add column if not exists owner_email text;
alter table whatsapp_bots add column if not exists owner_whatsapp text;
alter table whatsapp_bots add column if not exists company_name text;
alter table whatsapp_bots add column if not exists website text;
alter table whatsapp_bots add column if not exists business_description text;
alter table whatsapp_bots add column if not exists knowledge_text text;
alter table whatsapp_bots add column if not exists knowledge_status text;
alter table whatsapp_bots add column if not exists uploaded_file_name text;
alter table whatsapp_bots add column if not exists uploaded_file_mime text;
alter table whatsapp_bots add column if not exists uploaded_file_size_bytes bigint;
alter table whatsapp_bots add column if not exists uploaded_file_base64 text;
alter table whatsapp_bots add column if not exists assistant_id text;
alter table whatsapp_bots add column if not exists vector_store_id text;
alter table whatsapp_bots add column if not exists status text default 'pending_payment';
alter table whatsapp_bots add column if not exists payment_link text;
alter table whatsapp_bots add column if not exists payment_status text;
alter table whatsapp_bots add column if not exists payment_id text;
alter table whatsapp_bots add column if not exists phone_number text;
alter table whatsapp_bots add column if not exists created_at timestamptz default now();
alter table whatsapp_bots add column if not exists updated_at timestamptz;

create unique index if not exists idx_whatsapp_bots_bot_id_unique on whatsapp_bots(bot_id);
create index if not exists idx_whatsapp_bots_bot_id on whatsapp_bots(bot_id);

create table if not exists bot_training_files (
  id bigint generated by default as identity primary key,
  bot_id text,
  openai_file_id text,
  file_name text,
  file_size_bytes bigint,
  status text default 'active',
  created_at timestamptz default now()
);

alter table bot_training_files add column if not exists bot_id text;
alter table bot_training_files add column if not exists openai_file_id text;
alter table bot_training_files add column if not exists file_name text;
alter table bot_training_files add column if not exists file_size_bytes bigint;
alter table bot_training_files add column if not exists status text default 'active';
alter table bot_training_files add column if not exists created_at timestamptz default now();
create index if not exists idx_training_files_bot_id on bot_training_files(bot_id);

create table if not exists chat_history (
  id bigint generated by default as identity primary key,
  bot_id text,
  user_identifier text,
  user_message text,
  bot_response text,
  created_at timestamptz default now()
);

alter table chat_history add column if not exists bot_id text;
alter table chat_history add column if not exists user_identifier text;
alter table chat_history add column if not exists user_message text;
alter table chat_history add column if not exists bot_response text;
alter table chat_history add column if not exists created_at timestamptz default now();
create index if not exists idx_chat_history_bot_id on chat_history(bot_id);

create table if not exists smartbot_leads (
  id bigint generated by default as identity primary key,
  bot_id text,
  source_channel text,
  name text,
  email text,
  phone text,
  interest text,
  intent text,
  lead_temperature text,
  next_action text,
  follow_up_at timestamptz,
  conversation_summary text,
  created_at timestamptz default now(),
  updated_at timestamptz
);

alter table smartbot_leads add column if not exists bot_id text;
alter table smartbot_leads add column if not exists source_channel text;
alter table smartbot_leads add column if not exists name text;
alter table smartbot_leads add column if not exists email text;
alter table smartbot_leads add column if not exists phone text;
alter table smartbot_leads add column if not exists interest text;
alter table smartbot_leads add column if not exists intent text;
alter table smartbot_leads add column if not exists lead_temperature text;
alter table smartbot_leads add column if not exists next_action text;
alter table smartbot_leads add column if not exists follow_up_at timestamptz;
alter table smartbot_leads add column if not exists conversation_summary text;
alter table smartbot_leads add column if not exists created_at timestamptz default now();
alter table smartbot_leads add column if not exists updated_at timestamptz;
create index if not exists idx_smartbot_leads_bot_id on smartbot_leads(bot_id);
