[build]
  base = "notarizex-ai"
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/b/*"
  to = "/bot-publico.html"
  status = 200

[[redirects]]
  from = "/dashboard-cliente"
  to = "/dashboard-cliente.html"
  status = 200

[[redirects]]
  from = "/painel"
  to = "/dashboard-cliente.html"
  status = 200
