import React from 'react';
import {Text,View,TouchableOpacity,StyleSheet,ScrollView} from 'react-native';
import {colors,shadow} from './theme';
export function Screen({children,scroll=true}){const body=<View style={s.screen}>{children}</View>;return scroll?<ScrollView style={{flex:1,backgroundColor:colors.bg}} contentContainerStyle={{paddingBottom:24}}>{body}</ScrollView>:body}
export function H1({children}){return <Text style={s.h1}>{children}</Text>}
export function Muted({children}){return <Text style={s.muted}>{children}</Text>}
export function Card({children,green}){return <View style={[s.card,green&&s.greenCard]}>{children}</View>}
export function Button({children,onPress,secondary,variant}){const v=variant||(secondary?'dark':'green');return <TouchableOpacity onPress={onPress} style={[s.btn,v==='dark'&&s.btnDark,v==='ghost'&&s.btnGhost]}><Text style={[s.btnText,v==='dark'&&s.btnDarkText,v==='ghost'&&s.btnGhostText]}>{children}</Text></TouchableOpacity>}
export function Stat({label,value}){return <Card><Text style={s.stat}>{value}</Text><Muted>{label}</Muted></Card>}
export function Row({title,subtitle,right,onPress}){return <TouchableOpacity onPress={onPress} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text>{subtitle?<Muted>{subtitle}</Muted>:null}</View>{right?<Text style={s.right}>{right}</Text>:null}</TouchableOpacity>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg,padding:16},h1:{color:colors.text,fontSize:28,fontWeight:'900',marginBottom:6},muted:{color:colors.muted,fontSize:13,lineHeight:18},card:{backgroundColor:colors.card,borderColor:colors.line,borderWidth:1,borderRadius:18,padding:14,marginBottom:12,...shadow},greenCard:{backgroundColor:colors.green},btn:{backgroundColor:colors.green,borderRadius:14,padding:14,alignItems:'center',marginTop:8},btnDark:{backgroundColor:colors.soft,borderWidth:1,borderColor:colors.line},btnGhost:{backgroundColor:'transparent',padding:10},btnText:{color:'#020617',fontWeight:'900'},btnDarkText:{color:colors.text},btnGhostText:{color:colors.green,fontWeight:'900'},stat:{fontSize:25,fontWeight:'900',color:colors.text},row:{backgroundColor:colors.card,borderColor:colors.line,borderWidth:1,borderRadius:16,padding:14,marginBottom:10,flexDirection:'row',alignItems:'center'},rowTitle:{color:colors.text,fontWeight:'800',fontSize:15},right:{color:colors.green,fontWeight:'900'}});