import React from 'react';
import {Text,View,TouchableOpacity,StyleSheet} from 'react-native';
import {colors,shadow} from './theme';
export function Screen({children}){return <View style={s.screen}>{children}</View>}
export function H1({children}){return <Text style={s.h1}>{children}</Text>}
export function Muted({children}){return <Text style={s.muted}>{children}</Text>}
export function Card({children,green}){return <View style={[s.card,green&&s.greenCard]}>{children}</View>}
export function Button({children,onPress,secondary}){return <TouchableOpacity onPress={onPress} style={[s.btn,secondary&&s.btn2]}><Text style={[s.btnText,secondary&&s.btn2Text]}>{children}</Text></TouchableOpacity>}
export function Stat({label,value}){return <Card><Text style={s.stat}>{value}</Text><Muted>{label}</Muted></Card>}
export function Row({title,subtitle,right,onPress}){return <TouchableOpacity onPress={onPress} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text>{subtitle?<Muted>{subtitle}</Muted>:null}</View>{right?<Text style={s.right}>{right}</Text>:null}</TouchableOpacity>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg,padding:16},h1:{color:colors.text,fontSize:28,fontWeight:'900',marginBottom:6},muted:{color:colors.muted,fontSize:13},card:{backgroundColor:colors.card,borderColor:colors.line,borderWidth:1,borderRadius:18,padding:14,marginBottom:12,...shadow},greenCard:{backgroundColor:colors.green},btn:{backgroundColor:colors.green,borderRadius:14,padding:14,alignItems:'center',marginTop:8},btn2:{backgroundColor:colors.soft,borderWidth:1,borderColor:colors.line},btnText:{color:'#020617',fontWeight:'900'},btn2Text:{color:colors.text},stat:{fontSize:25,fontWeight:'900',color:colors.text},row:{backgroundColor:colors.card,borderColor:colors.line,borderWidth:1,borderRadius:16,padding:14,marginBottom:10,flexDirection:'row',alignItems:'center'},rowTitle:{color:colors.text,fontWeight:'800',fontSize:15},right:{color:colors.green,fontWeight:'900'}});