create table if not exists public.smartbot_whatsapp_onboarding_help (
  id bigint generated by default as identity primary key,
  bot_id text not null,
  company_name text,
  contact_name text,
  contact_email text,
  contact_whatsapp text,
  selected_mode text,
  status text not null default 'pending',
  source text not null default 'secure_connect',
  requested_at timestamptz not null default now(),
  last_requested_at timestamptz not null default now(),
  notified_at timestamptz,
  resolved_at timestamptz,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_sb_wa_help_bot_status
  on public.smartbot_whatsapp_onboarding_help(bot_id,status);

alter table public.smartbot_whatsapp_onboarding_help enable row level security;
revoke all on table public.smartbot_whatsapp_onboarding_help from anon, authenticated;
grant all on table public.smartbot_whatsapp_onboarding_help to service_role;
