import React,{useCallback,useState}from 'react';
import {TextInput,StyleSheet} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Clipboard from 'expo-clipboard';
import {Screen,H1,Muted,Card,Button,Row} from '../components';
import {colors} from '../theme';
import {openWhatsApp} from '../services/whatsapp';
function key(session){return 'smartbots:opportunities:'+(session?.botId||'local')}
export default function ProspectingScreen({session}){const[name,setName]=useState('');const[phone,setPhone]=useState('');const[note,setNote]=useState('');const[list,setList]=useState([]);const[status,setStatus]=useState('');async function load(){try{const raw=await AsyncStorage.getItem(key(session));setList(raw?JSON.parse(raw):[])}catch(e){setList([])}}useFocusEffect(useCallback(()=>{load()},[]));async function save(){const item={id:String(Date.now()),name:name.trim(),phone:phone.trim(),note:note.trim(),createdAt:new Date().toISOString()};if(!item.name&&!item.phone){setStatus('Informe pelo menos nome ou WhatsApp.');return}const next=[item,...list].slice(0,100);await AsyncStorage.setItem(key(session),JSON.stringify(next));setList(next);setName('');setPhone('');setNote('');setStatus('Oportunidade salva no app.')}async function copy(item){const msg='Olá! Tudo bem? Estou entrando em contato para entender como posso ajudar seu negócio.';await Clipboard.setStringAsync(msg)}return <Screen><H1>Oportunidades</H1><Muted>Cadastre contatos e oportunidades manualmente para acompanhar retornos e abrir conversas no WhatsApp.</Muted><Card><TextInput value={name} onChangeText={setName} placeholder="Nome do contato ou empresa" placeholderTextColor={colors.muted} style={st.input}/><TextInput value={phone} onChangeText={setPhone} placeholder="WhatsApp" placeholderTextColor={colors.muted} keyboardType="phone-pad" style={st.input}/><TextInput value={note} onChangeText={setNote} placeholder="Observação" placeholderTextColor={colors.muted} multiline style={[st.input,{height:84}]}/><Button onPress={save}>Salvar oportunidade</Button><Muted>{status}</Muted></Card><Muted>Oportunidades salvas</Muted>{list.length?list.map((x)=><Card key={x.id}><Row title={x.name||'Oportunidade'} subtitle={[x.phone,x.note].filter(Boolean).join(' • ')}/><Button variant="dark" onPress={()=>copy(x)}>Copiar mensagem</Button><Button variant="dark" onPress={()=>openWhatsApp(x.phone,'Olá! Tudo bem? Estou entrando em contato para entender como posso ajudar seu negócio.')}>Abrir WhatsApp</Button></Card>):<Row title="Nenhuma oportunidade ainda" subtitle="Adicione contatos para organizar seus próximos retornos."/>}</Screen>}
const st=StyleSheet.create({input:{backgroundColor:'#020617',borderColor:colors.line,borderWidth:1,borderRadius:14,padding:13,color:colors.text,marginBottom:10}});